create table public.bank_payment_events (
  id bigint generated by default as identity primary key,
  bank text not null check (bank in ('monobank', 'novapay')),
  external_id text not null,
  occurred_at timestamptz not null,
  amount numeric(14, 2) not null,
  balance numeric(14, 2),
  payer text not null default '',
  description text not null default '',
  comment text not null default '',
  created_at timestamptz not null default now(),
  unique (bank, external_id)
);

alter table public.bank_payment_events enable row level security;

revoke all on table public.bank_payment_events from public, anon, authenticated;
grant select on table public.bank_payment_events to authenticated;
grant all on table public.bank_payment_events to service_role;

create policy bank_payment_events_read_authenticated
on public.bank_payment_events
for select
to authenticated
using (lower(coalesce(auth.jwt() ->> 'email', '')) <> 'guest@gmail.com');

create function public.cleanup_bank_payment_events()
returns void
language sql
security definer
set search_path = public
as $$
  delete from public.bank_payment_events where occurred_at < now() - interval '7 days';
$$;

revoke all on function public.cleanup_bank_payment_events() from public, anon, authenticated;
grant execute on function public.cleanup_bank_payment_events() to service_role;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'bank_payment_events'
  ) then
    alter publication supabase_realtime add table public.bank_payment_events;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'bank_account_cache'
  ) then
    alter publication supabase_realtime add table public.bank_account_cache;
  end if;
end;
$$;
